application: performanceboard-public
version: 1
runtime: go
api_version: go1
threadsafe: true

handlers:
- url: /static
  static_dir: client/static
  application_readable: true
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /.*
  script: _go_app

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
